adding a safety mechanism and less often attempts

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,30 +1,31 @@
-# name: update data
+name: update data
 
-# on:
-#   schedule:
-#     - cron: '*/15 * * * *'
+on:
+  schedule:
+    - cron: '*/30 * * * *'
 
-# jobs:
-#   update:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - uses: actions/checkout@master
-#         with:
-#           persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-#           fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
-#       - run: |
-#           for i in {1..5}; do wget -q -O beanally.csv ${{ secrets.doc_url }} && break || sleep 5; done
-#       - run: if [[ $(wc -l <beanally.csv) -le 20 ]]; then exit 1; fi
-#       - name: Commit files
-#         continue-on-error: true
-#         run: |
-#           git config --local user.email "action@github.com"
-#           git config --local user.name "GitHub Action"
-#           git commit -m "Add website changes" -a || curl ${{ secrets.hc_url }}
-#       - name: Push changes
-#         uses: ad-m/github-push-action@master
-#         with:
-#           github_token: ${{ secrets.gh_token }}
-#           branch: main
-#       - name: crontab
-#         run: curl ${{ secrets.hc_url }}
+jobs:
+  update:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@master
+        with:
+          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+      - run: |
+          for i in {1..5}; do wget -q -O beanally.csv ${{ secrets.doc_url }} && break || sleep 5; done
+      - run: if [[ $(wc -l <beanally.csv) -le 20 ]]; then exit 1; fi # this is a check for an empty file
+      - run: if [[ $(cat beanally.csv |grep Petitions| wc -l) -le 20 ]]; then exit 1; fi # this is a check for reasonable content
+      - name: Commit files
+        continue-on-error: true
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git commit -m "Add website changes" -a || curl ${{ secrets.hc_url }}
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.gh_token }}
+          branch: main
+      - name: crontab
+        run: curl ${{ secrets.hc_url }}
